'use server';

/**
 * @fileOverview Main flow for the generateProjectIdea functionality.
 */

import { z } from 'zod';
import { callAI } from '@/ai/ai-instance'; // Do not modify ai-instance.ts

// Move schemas to a separate non-server file if needed
const GenerateProjectIdeaAIOutputSchema = z.object({
  idea: z.string().describe('Suggest a concise and actionable project idea suitable for freelance execution. Be creative!'),
  details: z.string().optional().describe('Provide 1-2 sentences elaborating on the suggested project idea.'),
  estimatedTimeline: z.string().describe('Estimate a realistic project delivery timeline (e.g., "3-5 days", "1-2 weeks").'),
  estimatedHours: z.number().positive({ message: "Estimated hours must be greater than 0." }).describe('Estimate the total number of hours required.'),
  requiredSkills: z.array(z.string()).optional().describe('List 1-3 key skills needed.'),
});

export async function generateProjectIdea(input: { industryHint?: string }): Promise<{
  idea: string;
  details?: string;
  estimatedTimeline: string;
  estimatedHours?: number;
  estimatedBaseCost?: number;
  platformFee?: number;
  totalCostToClient?: number;
  monthlySubscriptionCost?: number;
  reasoning?: string;
  status: 'success' | 'error';
  requiredSkills?: string[];
}> {
  try {
    const prompt = `
You are an expert freelance project designer.

Using the hint below, suggest a new, realistic freelance project idea that could be executed by a skilled freelancer.

Respond in JSON format matching exactly this structure:
{
  "idea": "...",
  "details": "...",
  "estimatedTimeline": "...",
  "estimatedHours": ...,
  "requiredSkills": ["...", "..."]
}

Hint (optional): ${input.industryHint ?? 'None'}
`;

    const modelResponse = await callAI('auto', prompt);
    const parsed = GenerateProjectIdeaAIOutputSchema.safeParse(JSON.parse(modelResponse));

    if (!parsed.success) {
      console.error('Validation error parsing AI output:', parsed.error);
      return {
        idea: '',
        estimatedTimeline: '',
        status: 'error',
      };
    }

    const { idea, details, estimatedTimeline, estimatedHours, requiredSkills } = parsed.data;

    const baseRatePerHour = 50;
    const estimatedBaseCost = estimatedHours ? estimatedHours * baseRatePerHour : undefined;
    const platformFee = estimatedBaseCost ? estimatedBaseCost * 0.15 : undefined;
    const totalCostToClient = estimatedBaseCost && platformFee ? estimatedBaseCost + platformFee : undefined;
    const monthlySubscriptionCost = totalCostToClient ? totalCostToClient * 0.1 : undefined;

    return {
      idea,
      details,
      estimatedTimeline,
      estimatedHours,
      estimatedBaseCost,
      platformFee,
      totalCostToClient,
      monthlySubscriptionCost,
      reasoning: 'Generated by AI based on the provided industry hint.',
      status: 'success',
      requiredSkills,
    };
  } catch (error: any) {
    console.error('Error generating project idea:', error?.message ?? error);
    return {
      idea: '',
      estimatedTimeline: '',
      status: 'error',
    };
  }
}
