
import type { Freelancer } from '@/types/freelancer';
import { Timestamp } from 'firebase/firestore';

export const dummyFreelancers: Freelancer[] = [
  {
    id: 'dev-react-001',
    name: 'Alice Johnson',
    email: 'alice.j@example.com',
    skills: ['React', 'TypeScript', 'Next.js', 'Node.js', 'GraphQL'],
    hourlyRate: 85,
    rating: 4.9,
    yearsOfExperience: 7,
    status: 'available',
    isLoggedIn: true,
    xp: 2500,
    createdAt: Timestamp.fromDate(new Date('2023-01-15')),
  },
  {
    id: 'design-uiux-002',
    name: 'Bob Williams',
    email: 'bob.w@example.com',
    skills: ['UI Design', 'UX Research', 'Figma', 'Prototyping', 'Design Systems'],
    hourlyRate: 75,
    rating: 4.8,
    yearsOfExperience: 5,
    status: 'busy',
    isLoggedIn: true,
    xp: 2200,
    createdAt: Timestamp.fromDate(new Date('2023-02-20')),
  },
  {
    id: 'dev-python-003',
    name: 'Charlie Brown',
    email: 'charlie.b@example.com',
    skills: ['Python', 'Django', 'Flask', 'Data Analysis', 'PostgreSQL'],
    hourlyRate: 90,
    rating: 4.9,
    yearsOfExperience: 8,
    status: 'available',
    isLoggedIn: true,
    xp: 3000,
    createdAt: Timestamp.fromDate(new Date('2023-03-10')),
  },
  {
    id: 'writer-copy-004',
    name: 'Diana Prince',
    email: 'diana.p@example.com',
    skills: ['Copywriting', 'Content Strategy', 'SEO', 'Marketing', 'Technical Writing'],
    hourlyRate: 65,
    rating: 4.7,
    yearsOfExperience: 6,
    status: 'offline',
    isLoggedIn: false,
    xp: 1800,
    createdAt: Timestamp.fromDate(new Date('2023-04-05')),
  },
  {
    id: 'dev-mobile-005',
    name: 'Ethan Hunt',
    email: 'ethan.h@example.com',
    skills: ['React Native', 'Swift', 'Kotlin', 'iOS', 'Android'],
    hourlyRate: 95,
    rating: 4.8,
    yearsOfExperience: 9,
    status: 'available',
    isLoggedIn: true,
    xp: 2800,
    createdAt: Timestamp.fromDate(new Date('2023-05-12')),
  },
  {
    id: 'data-ml-006',
    name: 'Fiona Glenanne',
    email: 'fiona.g@example.com',
    skills: ['Machine Learning', 'TensorFlow', 'PyTorch', 'Data Science', 'Python'],
    hourlyRate: 110,
    rating: 5.0,
    yearsOfExperience: 10,
    status: 'busy',
    isLoggedIn: true,
    xp: 4500,
    createdAt: Timestamp.fromDate(new Date('2023-06-21')),
  },
  {
    id: 'dev-vue-007',
    name: 'George Costanza',
    email: 'george.c@example.com',
    skills: ['Vue.js', 'Nuxt.js', 'JavaScript', 'CSS', 'HTML'],
    hourlyRate: 70,
    rating: 4.5,
    yearsOfExperience: 4,
    status: 'offline',
    isLoggedIn: false,
    xp: 1500,
    createdAt: Timestamp.fromDate(new Date('2023-07-18')),
  },
  {
    id: 'design-illustrator-008',
    name: 'Hela Odinsdottir',
    email: 'hela.o@example.com',
    skills: ['Illustration', 'Adobe Illustrator', 'Character Design', 'Digital Painting'],
    hourlyRate: 80,
    rating: 4.9,
    yearsOfExperience: 8,
    status: 'available',
    isLoggedIn: true,
    xp: 2600,
    createdAt: Timestamp.fromDate(new Date('2023-08-02')),
  },
  {
    id: 'devops-aws-009',
    name: 'Ian Malcolm',
    email: 'ian.m@example.com',
    skills: ['DevOps', 'AWS', 'Docker', 'Kubernetes', 'CI/CD'],
    hourlyRate: 120,
    rating: 4.9,
    yearsOfExperience: 12,
    status: 'available',
    isLoggedIn: true,
    xp: 3800,
    createdAt: Timestamp.fromDate(new Date('2023-09-14')),
  },
  {
    id: 'pm-agile-010',
    name: 'Jane Foster',
    email: 'jane.f@example.com',
    skills: ['Project Management', 'Agile', 'Scrum', 'Jira', 'Stakeholder Communication'],
    hourlyRate: 100,
    rating: 4.8,
    yearsOfExperience: 10,
    status: 'busy',
    isLoggedIn: true,
    xp: 3200,
    createdAt: Timestamp.fromDate(new Date('2023-10-30')),
  },
  {
    id: 'dev-go-011',
    name: 'Ken Adams',
    email: 'ken.a@example.com',
    skills: ['Go', 'Microservices', 'REST APIs', 'gRPC', 'Gin'],
    hourlyRate: 105,
    rating: 4.7,
    yearsOfExperience: 6,
    status: 'available',
    isLoggedIn: true,
    xp: 2900,
    createdAt: Timestamp.fromDate(new Date('2023-11-11')),
  },
  {
    id: 'qa-auto-012',
    name: 'Laura Palmer',
    email: 'laura.p@example.com',
    skills: ['QA Automation', 'Selenium', 'Cypress', 'Playwright', 'Testing Strategy'],
    hourlyRate: 75,
    rating: 4.6,
    yearsOfExperience: 5,
    status: 'offline',
    isLoggedIn: false,
    xp: 1900,
    createdAt: Timestamp.fromDate(new Date('2023-12-01')),
  },
  {
    id: 'dev-dotnet-013',
    name: 'Michael Scott',
    email: 'michael.s@example.com',
    skills: ['.NET', 'C#', 'Azure', 'Entity Framework', 'Blazor'],
    hourlyRate: 88,
    rating: 4.7,
    yearsOfExperience: 9,
    status: 'available',
    isLoggedIn: true,
    xp: 2400,
    createdAt: Timestamp.fromDate(new Date('2024-01-08')),
  },
  {
    id: 'video-editor-014',
    name: 'Nancy Wheeler',
    email: 'nancy.w@example.com',
    skills: ['Video Editing', 'Adobe Premiere Pro', 'After Effects', 'Color Grading'],
    hourlyRate: 78,
    rating: 4.8,
    yearsOfExperience: 6,
    status: 'available',
    isLoggedIn: true,
    xp: 2100,
    createdAt: Timestamp.fromDate(new Date('2024-02-14')),
  },
  {
    id: 'dev-ruby-015',
    name: 'Oscar Martinez',
    email: 'oscar.m@example.com',
    skills: ['Ruby', 'Ruby on Rails', 'Heroku', 'Sidekiq'],
    hourlyRate: 92,
    rating: 4.6,
    yearsOfExperience: 8,
    status: 'offline',
    isLoggedIn: false,
    xp: 2350,
    createdAt: Timestamp.fromDate(new Date('2024-03-03')),
  },
  {
    id: 'design-3d-016',
    name: 'Peter Parker',
    email: 'peter.p@example.com',
    skills: ['3D Modeling', 'Blender', 'ZBrush', 'Texturing', 'Rendering'],
    hourlyRate: 98,
    rating: 4.9,
    yearsOfExperience: 5,
    status: 'busy',
    isLoggedIn: true,
    xp: 3100,
    createdAt: Timestamp.fromDate(new Date('2024-04-01')),
  },
  {
    id: 'marketing-sem-017',
    name: 'Quinn Fabray',
    email: 'quinn.f@example.com',
    skills: ['SEM', 'Google Ads', 'PPC', 'Google Analytics', 'A/B Testing'],
    hourlyRate: 82,
    rating: 4.7,
    yearsOfExperience: 7,
    status: 'available',
    isLoggedIn: true,
    xp: 2050,
    createdAt: Timestamp.fromDate(new Date('2024-05-20')),
  },
  {
    id: 'dev-java-018',
    name: 'Rachel Green',
    email: 'rachel.g@example.com',
    skills: ['Java', 'Spring Boot', 'Microservices', 'Hibernate', 'Maven'],
    hourlyRate: 95,
    rating: 4.8,
    yearsOfExperience: 10,
    status: 'available',
    isLoggedIn: true,
    xp: 2750,
    createdAt: Timestamp.fromDate(new Date('2024-06-15')),
  },
  {
    id: 'sec-analyst-019',
    name: 'Steve Rogers',
    email: 'steve.r@example.com',
    skills: ['Cybersecurity', 'Penetration Testing', 'Wireshark', 'Nmap', 'Security Analysis'],
    hourlyRate: 115,
    rating: 4.9,
    yearsOfExperience: 11,
    status: 'offline',
    isLoggedIn: false,
    xp: 3500,
    createdAt: Timestamp.fromDate(new Date('2024-07-04')),
  },
  {
    id: 'design-motion-020',
    name: 'Tony Stark',
    email: 'tony.s@example.com',
    skills: ['Motion Graphics', 'After Effects', 'Cinema 4D', 'Animation'],
    hourlyRate: 130,
    rating: 5.0,
    yearsOfExperience: 15,
    status: 'busy',
    isLoggedIn: true,
    xp: 5200,
    createdAt: Timestamp.fromDate(new Date('2024-07-21')),
  },
];
