// REMOVED 'use server'; directive

import { genkit } from 'genkit';
import { googleAI } from '@genkit-ai/googleai';
import { openAI } from 'genkitx-openai';
import { anthropic } from 'genkitx-anthropic';
import { z } from 'zod';

// --- Environment Variables ---
const GOOGLE_API_KEY    = process.env.GOOGLE_API_KEY;
const OPENAI_API_KEY    = process.env.OPENAI_API_KEY;
const ANTHROPIC_API_KEY = process.env.ANTHROPIC_API_KEY;

// --- AI Plugin Configuration ---
const plugins = [];

if (GOOGLE_API_KEY) {
    plugins.push(googleAI({ apiKey: GOOGLE_API_KEY }));
    console.log('[AI Configuration] Google AI plugin configured.');
} else {
    console.warn('[AI Configuration] GOOGLE_API_KEY is missing. Google AI features will fail.');
}

if (OPENAI_API_KEY) {
    plugins.push(openAI({ apiKey: OPENAI_API_KEY }));
    console.log('[AI Configuration] OpenAI plugin configured.');
} else {
    // console.warn('[AI Configuration] OPENAI_API_KEY is missing. OpenAI features will be unavailable.');
}

if (ANTHROPIC_API_KEY) {
    plugins.push(anthropic({ apiKey: ANTHROPIC_API_KEY }));
     console.log('[AI Configuration] Anthropic plugin configured.');
} else {
    // console.warn('[AI Configuration] ANTHROPIC_API_KEY is missing. Anthropic features will be unavailable.');
}

if (!plugins.length) {
  console.error('[AI Configuration] No API keys found. AI functionality will be severely limited or fail entirely.');
  // Potentially throw an error here if no plugins can be initialized
  // throw new Error('No AI plugins could be configured due to missing API keys.');
}

// Initialize Genkit
export const ai = genkit({
  plugins,
  // logLevel: 'debug', // Optional: for detailed logs
});


// --- Model Selection Logic ---
// Returns a Genkit-compatible model string (e.g., 'googleai/gemini-1.5-flash').
export async function chooseModelBasedOnPrompt(promptContent: string): Promise<string> {
  const promptLength = promptContent.length;
  const promptLower = promptContent.toLowerCase();
  const availableModels: string[] = [];

  // Populate availableModels based on which keys are present
  if (GOOGLE_API_KEY)    availableModels.push('googleai/gemini-1.5-flash');
  if (OPENAI_API_KEY)    availableModels.push('openai/gpt-4o', 'openai/gpt-3.5-turbo');
  if (ANTHROPIC_API_KEY) availableModels.push('anthropic/claude-3-5-sonnet-20240620', 'anthropic/claude-3-haiku-20240307');

  if (availableModels.length === 0) {
    console.error('[AI Model Selection] No models available due to missing API keys.');
    throw new Error('No AI models available.'); // Throw error if no models can be used
  }

  // Prioritize specific models based on keywords if available
  if ( (promptLower.includes('graphic design') || promptLower.includes('visual critique')) && availableModels.includes('openai/gpt-4o') ) {
    return 'openai/gpt-4o';
  }
  if ( (promptLower.includes('code') || promptLower.includes('```') || promptLower.includes('debug')) && availableModels.includes('openai/gpt-4o') ) {
     return 'openai/gpt-4o';
  }
  if ( (promptLength > 1500 || promptLower.includes('analysis') || promptLower.includes('report')) && availableModels.includes('anthropic/claude-3-5-sonnet-20240620') ) {
    return 'anthropic/claude-3-5-sonnet-20240620';
  }
  if ( (promptLower.includes('creative') || promptLower.includes('story') || promptLower.includes('marketing')) && availableModels.includes('anthropic/claude-3-5-sonnet-20240620') ) {
      return 'anthropic/claude-3-5-sonnet-20240620';
  }

  // Fallback logic - Prioritize Google AI if available and no other specific match
  if (availableModels.includes('googleai/gemini-1.5-flash')) {
    return 'googleai/gemini-1.5-flash'; // Good general-purpose default
  }
  // Other fallbacks if Google isn't available
  if (availableModels.includes('anthropic/claude-3-haiku-20240307')) {
     return 'anthropic/claude-3-haiku-20240307'; // Faster/cheaper alternative
  }
  if (availableModels.includes('openai/gpt-3.5-turbo')) {
    return 'openai/gpt-3.5-turbo'; // Another fallback
  }

  // If somehow none of the specific fallbacks match, return the first available
  console.warn("[AI Model Selection] No specific model match found, returning first available:", availableModels[0]);
  return availableModels[0];
}


// --- Prompt Templates ---

// Validation Prompt Template
const VALIDATION_PROMPT_TEXT = `You are an AI quality assurance assistant.
Review the following ORIGINAL PROMPT and the RESPONSE generated by another AI.
Is the RESPONSE an acceptable, relevant, and high-quality answer to the ORIGINAL PROMPT?
Answer ONLY with "Acceptable" or "Unacceptable".

ORIGINAL PROMPT:
---
{{{originalPrompt}}}
---

RESPONSE:
---
{{{responseToValidate}}}
---

Assessment (Acceptable/Unacceptable):`;

// Define the validation prompt using genkit
const validationPrompt = ai.definePrompt({
    name: 'validateAIResponse',
    input: { schema: z.object({ originalPrompt: z.string(), responseToValidate: z.string() }) },
    output: { schema: z.string().describe("Either 'Acceptable' or 'Unacceptable'") },
    prompt: VALIDATION_PROMPT_TEXT,
});


// --- Core AI Call Function with Cross-Validation ---
export async function callAI(originalPrompt: string, modelOverride?: string): Promise<string> {
  let primaryModelId: string;

  // 1. Choose Primary Model
  try {
    // Use override if provided, otherwise choose based on prompt content
    primaryModelId = modelOverride ?? await chooseModelBasedOnPrompt(originalPrompt);
    console.log(`[AI Call - Primary] Using model: ${primaryModelId}`);
  } catch (err: any) {
    console.error('[AI Call Error] Failed to select primary model:', err.message);
    // Return a user-friendly error message
    return `Error: Could not select an AI model. ${err.message}`;
  }

  // 2. Generate Primary Response
  let primaryResponse: string;
  try {
    console.log(`[AI Call - Primary] Calling model ${primaryModelId}...`);
    // Use the selected model ID to generate the response
    const { text } = await ai.generate({ model: primaryModelId, prompt: originalPrompt });
    if (!text) throw new Error(`Primary AI model (${primaryModelId}) returned an empty response.`);
    primaryResponse = text;
    console.log(`[AI Call - Primary] Response received from ${primaryModelId}. Length: ${primaryResponse.length}`);
  } catch (err: any) {
    console.error(`[AI Call Error - Primary ${primaryModelId}] ${err.message}`);
    // Return a user-friendly error message including the model that failed
    return `Error generating response from ${primaryModelId}: ${err.message}`;
  }

  // 3. Select Validation Models
  const availableModels: string[] = [];
  if (GOOGLE_API_KEY)    availableModels.push('googleai/gemini-1.5-flash');
  if (OPENAI_API_KEY)    availableModels.push('openai/gpt-4o', 'openai/gpt-3.5-turbo');
  if (ANTHROPIC_API_KEY) availableModels.push('anthropic/claude-3-5-sonnet-20240620', 'anthropic/claude-3-haiku-20240307');

  // Get up to two *different* models for validation
  const validationModels = availableModels
    .filter(modelId => modelId !== primaryModelId) // Exclude the primary model
    .slice(0, 2); // Take the first two available different models

  // 4. Perform Cross-Validation (if enough distinct models are available)
  if (validationModels.length < 1) {
    console.warn(`[AI Call - Validation] Not enough distinct models available to perform cross-validation for primary model ${primaryModelId}. Skipping validation.`);
    return primaryResponse; // Skip validation if fewer than 2 models total (primary + validator)
  }

  console.log(`[AI Call - Validation] Using validators: ${validationModels.join(', ')}`);
  let validationPassedCount = 0;
  let validationFailedCount = 0;

  for (const validationModelId of validationModels) {
    console.log(`[AI Call - Validation] Requesting validation from ${validationModelId}...`);
    try {
      // Call the defined validationPrompt with the specific validation model
      const { output: validationResult } = await validationPrompt(
        { originalPrompt, responseToValidate: primaryResponse },
        { model: validationModelId } // Specify the validation model
      );

      if (!validationResult) {
         throw new Error(`Validation model ${validationModelId} returned an empty result.`);
      }

      if (validationResult.toLowerCase().includes('acceptable')) {
        validationPassedCount++;
        console.log(`[AI Call - Validation] ${validationModelId} assessed response as: Acceptable`);
      } else {
        validationFailedCount++;
        console.warn(`[AI Call - Validation] ${validationModelId} assessed response as: Unacceptable (Result: ${validationResult})`);
      }
    } catch (err: any) {
      console.error(`[AI Call Error - Validation ${validationModelId}] Failed to get validation: ${err.message}`);
      // Treat validation error as a potential failure, but don't stop the whole process
      validationFailedCount++; // Count errors as failures for safety
    }
  }

  // 5. Evaluate Validation Results
  // Require at least one 'Acceptable' and no 'Unacceptable' for the response to pass.
  // Adjust logic as needed (e.g., require unanimous acceptance).
  if (validationPassedCount > 0 && validationFailedCount === 0) {
      console.log(`[AI Call - Validation] Validation passed (${validationPassedCount} acceptable, ${validationFailedCount} unacceptable).`);
      return primaryResponse;
  } else {
      console.error(`[AI Call - Validation] Validation FAILED (${validationPassedCount} acceptable, ${validationFailedCount} unacceptable). Primary response from ${primaryModelId} may be unreliable.`);
      // Consider returning the primary response with a warning, or a specific error message
      // return `Error: AI response failed cross-validation. Primary model: ${primaryModelId}.`;
      // For now, return primary response but log the failure. In production, might throw error or add warning metadata.
      console.error(`Cross-validation failed for prompt: "${originalPrompt.substring(0, 100)}..."`);
      // Prepend a warning to the response?
      // return `[Warning: Cross-validation failed] ${primaryResponse}`;
      return primaryResponse; // Return primary response despite validation failure, but log it.
  }
}


// --- Static Prompt Definitions (Examples - Keep or remove as needed) ---
// These prompts use the default model configured in `genkit` unless overridden
export const projectDecompositionPrompt = ai.definePrompt({
  name: 'projectDecomposition',
  input:  { schema: z.object({ brief: z.string() }) },
  output: { schema: z.string().describe('Markdown checklist') },
  // Uses default model unless overridden when called
  prompt: ({ brief }) => [{
    text: `You are an expert AI project manager. Decompose this brief into clear, ordered microtasks (markdown checklist format):

${brief}`
  }],
});

export const generateProjectIdeaPrompt = ai.definePrompt({
    name: 'generateProjectIdea',
    input: { schema: z.object({ industryHint: z.string().optional() }) },
    output: {
      schema: z.object({
        idea:             z.string().min(1),
        details:          z.string().min(1), // Made details required as well
        estimatedTimeline:z.string().min(1),
        estimatedHours:   z.number().min(0.1, "Estimated hours must be at least 0.1"), // Correct use of min
        requiredSkills:   z.array(z.string().min(1)).min(1).max(5),
      })
    },
    // Specify a model if needed, otherwise uses genkit default
    // model: 'googleai/gemini-1.5-flash',
    prompt: ({ industryHint }) => [{
      text: `Generate a single, valid JSON object representing a freelance project idea.

CRITICAL: Your entire response MUST be ONLY a single, valid JSON object.
Do NOT include ANY introductory text, concluding text, explanations, apologies, or markdown formatting like \`\`\`json.
Start the response immediately with '{' and end it immediately with '}'.

Strictly adhere to this structure and ensure all fields are present and non-empty:
{
  "idea": "string (short, catchy project title, non-empty)",
  "details": "string (detailed project description, non-empty, min 10 chars)",
  "estimatedTimeline": "string (e.g., '3-5 days', '1 week', non-empty)",
  "estimatedHours": number (must be >= 0.1),
  "requiredSkills": ["array of 1-5 skill strings (non-empty)"]
}
${industryHint ? `Industry Hint: Focus on '${industryHint}'.` : ''}
Return ONLY the JSON. Verify the structure and types carefully, especially 'estimatedHours' (number >= 0.1) and ensure all string fields are non-empty.`
    }],
    // Config to enforce JSON output if the model supports it (Gemini does)
     config: {
        responseFormat: 'json',
        // temperature: 0.7, // Adjust temperature if needed
     }
});


export const matchFreelancerPrompt = ai.definePrompt({
  name: 'matchFreelancers',
  input:  { schema: z.object({ projectBrief: z.string(), freelancerId: z.string().optional() }) },
  output: { schema: z.string().describe('Matching JSON and reasoning') },
  // Uses default model unless overridden when called
  prompt: ({ projectBrief, freelancerId }) => [{
    text: `Match this project brief to an ideal freelancer. Brief: ${projectBrief}` +
          (freelancerId ? `
Client ID: ${freelancerId}` : '') }],
});


// Note: Fine-tuning logic (getUserFineTunedModel, triggerFineTuningJob) is removed
// as it's complex and requires significant infrastructure beyond basic API calls.
// It would typically involve dedicated services and asynchronous job handling.
    

